import type { TemplateStore } from '@/components/templates/types'

export const SAMPLE_STORE: TemplateStore = {
  id: 1,
  ordering_enabled: true,
  name: 'Mario’s Pizzeria',
  alias: 'marios-pizzeria',
  description: 'Authentic Italian wood-fired pizzas. Family recipe since 1985.',
  phone: '+213 555 123 456',
  email: 'hello@mariospizza.dz',
  address: '12 Rue des Oliviers, Alger Centre, Algeria',
  logo: null,
  cover: null,
  cover_image: null,
  avg_rating: 4.5,
  reviews_count: 128,
  opening_hours: {
    monday: { open: '11:00', close: '23:00' },
    tuesday: { open: '11:00', close: '23:00' },
    wednesday: { open: '11:00', close: '23:00' },
    thursday: { open: '11:00', close: '23:00' },
    friday: { open: '15:00', close: '23:00' },
    saturday: { open: '11:00', close: '23:00' },
    sunday: { open: '11:00', close: '23:00' },
  },
  wilaya: null,
  daira: null,
  commune: null,
  latitude: null,
  longitude: null,
  type_categories: [],
  phones: [],
  social_links: [],
  avg_prep_time: null,
  base_delivery_fee: null,
  delivery_zone_radius: null,
  avg_delivery_time_per_km: null,
  allows_pre_orders: false,
  pre_order_lead_time_hours: null,
  is_paused: false,
  pause_note: null,
  images: [],
  offers: [],
  posts: [],
  banners: [],
  reservation_enabled: false,
  badges: [
    { id: 1, name: 'Top Rated', color: '#10b981', icon: 'star' },
    { id: 2, name: 'Fast Prep', color: '#3b82f6', icon: 'bolt' },
  ],
  staff: [
    { name: 'Mario Rossi', role: 'Head Chef' },
    { name: 'Luigi Bianchi', role: 'Sous Chef' },
    { name: 'Sophie Martin', role: 'Pastry Chef' },
  ],
  foods: [
    { id: 1, store_id: 1, name: 'Margherita Pizza', description: 'San Marzano tomatoes, fresh mozzarella, olive oil, basil.', price: 700, price_usd: 4.50, price_eur: 4.00, new_price: null, image: null, category_id: 1, is_offer: false, cooking_time: 12 },
    { id: 2, store_id: 1, name: 'Pepperoni Pizza', description: 'Spicy pepperoni, mozzarella, tomato sauce on hand-tossed dough.', price: 850, price_usd: 5.50, price_eur: 5.00, new_price: 680, image: null, category_id: 1, is_offer: true, cooking_time: 15 },
    { id: 3, store_id: 1, name: 'Vegetarian Pizza', description: 'Bell peppers, mushrooms, olives, sweet corn, mozzarella.', price: 800, price_usd: 5.00, price_eur: 4.50, new_price: null, image: null, category_id: 1, is_offer: false, cooking_time: 14 },
    { id: 4, store_id: 1, name: 'Orange Juice', description: 'Freshly squeezed sweet organic oranges.', price: 200, price_usd: null, price_eur: null, new_price: null, image: null, category_id: 2, is_offer: false, cooking_time: 3 },
    { id: 5, store_id: 1, name: 'Coca-Cola 330ml', description: 'Ice cold refreshing soft drink.', price: 100, price_usd: null, price_eur: null, new_price: null, image: null, category_id: 2, is_offer: false, cooking_time: 1 },
    { id: 6, store_id: 1, name: 'Classic Cheeseburger', description: 'Beef patty, melted cheddar, pickles, mustard, ketchup.', price: 450, price_usd: 3.00, price_eur: 2.50, new_price: null, image: null, category_id: 3, is_offer: false, cooking_time: 8 },
    { id: 7, store_id: 1, name: 'Tiramisu', description: 'Coffee-soaked ladyfingers, mascarpone cream, cocoa.', price: 350, price_usd: 2.50, price_eur: 2.00, new_price: null, image: null, category_id: 4, is_offer: false, cooking_time: 5 },
  ],
  reviews: [
    { id: 1, rating: 5, comment: 'Incredible pizza! Perfectly crispy crust and fresh ingredients.', user: 'Ahmed K.', avatar: null, created_at: '2026-06-15T19:30:00Z' },
    { id: 2, rating: 4, comment: 'Great atmosphere and friendly staff. Delicious pepperoni pizza.', user: 'Sarah M.', avatar: null, created_at: '2026-06-10T20:15:00Z' },
    { id: 3, rating: 5, comment: 'Delivery arrived hot and fresh. The tiramisu is a must-try!', user: 'Youssef B.', avatar: null, created_at: '2026-06-05T21:00:00Z' },
  ],
}
